[build]
  publish = "public"
  command = ""  # No build command needed for static files

# Disable secrets scanning for our environment variables
[secrets]
  scan = false

[build.environment]
  NODE_VERSION = "18"

# Redirects for client-side routing
[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-dashboard"
  to = "/admin-dashboard.html"
  status = 200

# Catch-all for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
